# Generated by Django 2.0.3 on 2018-03-20 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('construct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.World'),
        ),
    ]
