# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_world_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField(max_length=255)),
                ('instance_type', models.CharField(default='article', max_length=15)),
                ('instance_id', models.IntegerField()),
            ],
        ),
    ]
