# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0003_auto_20170907_1844'),
        ('articles', '0004_delete_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='world_id',
        ),
        migrations.AddField(
            model_name='article',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.World'),
        ),
    ]
