# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('world_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='world',
            name='picture',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
