# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0003_auto_20170907_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
