# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0004_auto_20170907_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='world',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='world',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
