# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0005_auto_20170923_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ('created_at',)},
        ),
    ]
