# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0006_auto_20171104_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='picture',
            field=models.URLField(blank=True, default='http://res.cloudinary.com/drjvh4g6x/image/upload/v1506594585/browseruploads/nih2x4dfjj31jpa3tmu9.jpg', max_length=255, null=True),
        ),
    ]
