# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170901_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
