# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170923_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicturesRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_type', models.CharField(max_length=16)),
                ('instance_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='instance_id',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='instance_type',
        ),
        migrations.AddField(
            model_name='picturesrelationship',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Picture'),
        ),
    ]
