# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170923_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturesrelationship',
            name='redirect',
            field=models.CharField(default='/', max_length=255),
        ),
    ]
