# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('user', '0007_picturesrelationship_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='chats',
            field=models.ManyToManyField(to='chat.ChatRoom'),
        ),
    ]
