# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_account_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='chats',
        ),
    ]
